config/routes.rb
Rails.application.routes.draw do
  resources :projects

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'landing#index', as: :landing
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user
  has_many :projects
end

app/models/participation.rb
class Participation < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :company
  has_many :participations
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  belongs_to :user_type
  has_one :company
  has_many :participations

end

app/models/user_type.rb
class UserType < ApplicationRecord
  has_many :users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:user_type_id])
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController

  def index
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show]
  def index
    @projects = Project.all
  end

  def show
    
  end

  def new
  end

  private
  def set_project
    @project = Project.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/landing/index.html.haml
.overlay
  .overlay__img.bg-landing.bg-animation
  .overlay__bg.blue
  .overlay__content
    .landing__overlay.text-center
      %h2.text-white.toBottom
        Lorem ipsum dolor sit amet, consectetur adipiscing elit
      %p.text-white.toTop
        minim veniam, quis nostrud exercitation ullamco
      %p.text-white.toTop
        minim veniam, quis nostrud exercitation
      %p.text-white.toTop
        minim veniam, quis nostrud
      %button.btn.btn__large.btn--green.toRight
        GO!
  .landing__arrow.flex.flex-absCenter.toTop#btnArrow
    %i.fa.fa-chevron-down
%section.landing__section.landing__intro.flex.flex-absCenter#introSection
  %h3.text-center
    WE BELIEVE TO CREATE THE IMPOSSIBLE
  %p.text-center
    Lid est laborum dolo rumes fugats untras. Etharums ser quidem rerum facilis dolores nemis omnis fugats vitaes nemo minima rerums unsers sadips amets.
%section.landing__section.landing__features.flex
  .feature
    .feature__icon.text-green
      %i.fa.fa-users
    .feature__content
      %h4
        PROYECTOS REALES
      %p
        Lorem ipsum dolor sit amet, consectetur.
        %br
        adipiscing elit "Lorem ipsum dolor sit
        %br
        Lorem ipsum dolor sit amet, conse
  .feature
    .feature__icon.text-blue
      %i.fa.fa-laptop
    .feature__content
      %h4
        PROYECTOS REALES
      %p
        Lorem ipsum dolor sit amet, consectetur.
        %br
        adipiscing elit "Lorem ipsum dolor sit
        %br
        Lorem ipsum dolor sit amet, conse
  .feature
    .feature__icon.text-red
      %i.fa.fa-mobile
    .feature__content
      %h4
        PROYECTOS REALES
      %p
        Lorem ipsum dolor sit amet, consectetur.
        %br
        adipiscing elit "Lorem ipsum dolor sit
        %br
        Lorem ipsum dolor sit amet, conse
%section.landing__section.landing__steps
  .landing__steps__title
    %h4
      ¿CÓMO FUNCIONA?
    %p
      Lorem ipsum dolor sit amet Lorem ipsum Lorem Lorem ipsum dolor sit amet Lorem ipsum Lorem. Lorem ipsum dolor sit amet Lorem ipsum Lorem Lorem ipsum dolor sit amet Lorem ipsum Lorem.
  .landing__steps__bg
    = image_tag 'landing/steps.jpg'
  .landing__steps__info
    .step
      .step__title
        %h3
          %i.fa.fa-user-o
          LOREM IPSUM DOLOR SIT AMET AMET
      .step__content
        Lorem ipsum dolor sit amet Lorem ipsum Lorem consectetur adipiscing elit, sed elit, sed
        %br
        consectetur adipiscing elit, sed elit, sed consectetur adipiscing elit, sed elit, sed
        %br
        consectetur adipiscing elit, sed elit consectetur adipiscing elit, sed elit, sed
    .step
      .step__title
        %h3
          %i.fa.fa-handshake-o
          LOREM IPSUM DOLOR SIT AMET AMET
      .step__content
        Lorem ipsum dolor sit amet Lorem ipsum Lorem consectetur adipiscing elit, sed elit, sed
        %br
        consectetur adipiscing elit, sed elit, sed consectetur adipiscing elit, sed elit, sed
        %br
        consectetur adipiscing elit, sed elit consectetur adipiscing elit, sed elit, sed
    .step
      .step__title
        %h3
          %i.fa.fa-rocket
          LOREM IPSUM DOLOR SIT AMET AMET
      .step__content
        Lorem ipsum dolor sit amet Lorem ipsum Lorem consectetur adipiscing elit, sed elit, sed
        %br
        consectetur adipiscing elit, sed elit, sed consectetur adipiscing elit, sed elit, sed
        %br
        consectetur adipiscing elit, sed elit consectetur adipiscing elit, sed elit, sed
    .landing__steps__actions
      %button.btn.btn__normal.btn--blue--inverted
        Consectetur adipiscing
%section.landing__section.landing__team
  .landing__team__title
    %h5
      CONOCE A NUESTRO EQUIPO
    %h3
      LOREM IPSUM LOREM IPSUM
    %p
      On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound.
  .landing__team__container
    .member
      .member__info
        %a{href: '#'}
          %i.fa.fa-facebook
        %a{href: '#'}
          %i.fa.fa-github
        %a{href: '#'}
          %i.fa.fa-twitter
      .member__img
        = image_tag 'landing/member.png'
      .member__content
        %h4
          NICOLAS OTAMENDI
          %br
          %span
            Developer
    .member
      .member__info
        %a{href: '#'}
          %i.fa.fa-facebook
        %a{href: '#'}
          %i.fa.fa-github
        %a{href: '#'}
          %i.fa.fa-twitter
      .member__img
        = image_tag 'landing/member.png'
      .member__content
        %h4
          NICOLAS OTAMENDI
          %br
          %span
            Developer
    .member
      .member__info
        %a{href: '#'}
          %i.fa.fa-facebook
        %a{href: '#'}
          %i.fa.fa-github
        %a{href: '#'}
          %i.fa.fa-twitter
      .member__img
        = image_tag 'landing/member.png'
      .member__content
        %h4
          NICOLAS OTAMENDI
          %br
          %span
            Developer
    .member
      .member__info
        %a{href: '#'}
          %i.fa.fa-facebook
        %a{href: '#'}
          %i.fa.fa-github
        %a{href: '#'}
          %i.fa.fa-twitter
      .member__img
        = image_tag 'landing/member.png'
      .member__content
        %h4
          NICOLAS OTAMENDI
          %br
          %span
            Developer
    .member
      .member__info
        %a{href: '#'}
          %i.fa.fa-facebook
        %a{href: '#'}
          %i.fa.fa-github
        %a{href: '#'}
          %i.fa.fa-twitter
      .member__img
        = image_tag 'landing/member.png'
      .member__content
        %h4
          NICOLAS OTAMENDI
          %br
          %span
            Developer
    .member
      .member__info
        %a{href: '#'}
          %i.fa.fa-facebook
        %a{href: '#'}
          %i.fa.fa-github
        %a{href: '#'}
          %i.fa.fa-twitter
      .member__img
        = image_tag 'landing/member.png'
      .member__content
        %h4
          NICOLAS OTAMENDI
          %br
          %span
            Developer
%section.landing__section.landing__contact
  %h2
    Tomémonos un café
    %i.fa.fa-coffee
  %form.form
    .form__col-5
      .field
        %label
          Nombre:
        %input{ type: 'text' }
      .field
        %label
          Email:
        %input{ type: 'email' }
    .form__col-5
      .field
        %label
          Mensaje:
        %textarea

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Glape
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'app'
  %body
    %header.header
      .header__logo.cursor-pointer#headerLogo
        %h2
          Glape
      %nav.menu
        %ul
          %li.menu__link
            = link_to('Proyectos', projects_path)
          - unless user_signed_in?
            %li.menu__link
              = link_to('Iniciar sesión', new_user_session_path)
            %li.menu__link
              = link_to('Registro', new_user_registration_path)
          - if user_signed_in?
            %li.menu__link
              = link_to('Cerrar sesión', destroy_user_session_path, method: :delete)
    = yield
    %footer.landing__footer.bg-black
      .flex.flex-absCenter
        .social-icon
          %i.fa.fa-facebook
        .social-icon
          %i.fa.fa-twitter
        .social-icon
          %i.fa.fa-instagram
        .social-icon
          %i.fa.fa-linkedin
      %h3.text-center.text-white.text-mogra.margin-none
        Glape

app/views/projects/index.html.haml
#projects__index
  .list
    - @projects.each do |project|
      = link_to project_path(id: project.id) do
        .title
          %b
            = project.title
        .body
          = project.body

app/views/projects/new.html.haml
%h1 Projects#new
%p Find me in app/views/projects/new.html.haml

app/views/projects/show.html.haml
%h1
  = @project.title
%p
  = @project.body